#!/bin/bash

set -e

root_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/.."
platform=`uname -a | awk '{print tolower($1)}'`
arch=`uname -m`
version="2.5.1.0"
url="https://github.com/AidpProject/Aidpcoin/archive/refs/tags"
tag="v2.5.1"

tarball_name="v1.0.1.tar.gz"
binary_url="${url}/${tarball_name}"
shasums_url="${url}/${tag}/SHA256SUMS.asc"

download_aidpd() {

    cd "${root_dir}/bin"

    echo "Downloading aidpcoin: ${binary_url}"

    is_curl=true
    if hash curl 2>/dev/null; then
        curl --fail -I $binary_url >/dev/null 2>&1
    else
        is_curl=false
        wget --server-response --spider $binary_url >/dev/null 2>&1
    fi

    if test $? -eq 0; then
        if [ "${is_curl}" = true ]; then
            curl -L $binary_url > $tarball_name
            curl -L $shasums_url > SHA256SUMS.asc
        else
            wget $binary_url
            wget $shasums_url
        fi
        if test -e "${tarball_name}"; then
            echo "Unpacking aidpcoin distribution"
            tar -xvzf $tarball_name
            if test $? -eq 0; then
                ln -sf "aidp-${version}/bin/aidpd"
                return;
            fi
        fi
    fi
    echo "Aidpcoin binary distribution could not be downloaded"
    exit -1
}



download=1
verify=0


if [ "${download}" = 1 ]; then
    download_aidpd
fi


exit 0